apiVersion: v1
kind: ConfigMap
metadata:
  name: guestbook
data:
  application.yml: |-
    spring.data.cassandra.contact-points: cassandra.default
    spring.data.cassandra.port: 9042
    spring.data.cassandra.keyspace-name: guestbook
    spring.data.cassandra.local-datacenter: datacenter1
    spring.data.cassandra.schema-action: create-if-not-exists
    spring.data.cassandra.rest.basePath: /api

---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: spring-configmap-secret
# type: Opaque
# data:
#   welcome.topSecret: dG9wIGxldmVsIHNlY3JldHM=
