apiVersion: v1
kind: Service
metadata:
  name: guestbook
spec:
  selector:
    app: guestbook
  ports:
    - port: 8081
      targetPort: 8081

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: guestbook
spec:
  replicas: 1
  selector:
    matchLabels:
      app: guestbook
  template:
    metadata:
      labels:
        app: guestbook
    spec:
      serviceAccountName: guestbook-sa
      containers:
        - name: guestbook
          image: guestbook
          imagePullPolicy: Never
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
          ports:
            - containerPort: 8081
              name: http
            - containerPort: 8082
              name: actuator
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: actuator
            initialDelaySeconds: 120
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: actuator
          volumeMounts:
            - mountPath: /config
              name: guestbook
            # - mountPath: /etc/secret
            #   name: spring-configmap-secret

      volumes:
        - name: guestbook
          configMap:
            name: guestbook
        # - name: spring-configmap-secret
        #   secret:
        #       secretName: spring-configmap-secret
