# rbac.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  #  namespace: default
  name: guestbook-reader
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources:
      ["pods", "configmaps", "secrets", "services", "endpoints", "namespaces"]
    verbs: ["get", "watch", "list"]

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: guestbook-sa
#  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: guestbook-role-binding
#  namespace: default
subjects:
  - kind: ServiceAccount
    name: guestbook-sa
#    namespace: default
roleRef:
  kind: Role
  name: guestbook-reader
  apiGroup: rbac.authorization.k8s.io
